name: Mceutik Website API Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Build and push mceutik image
    - name: Build and push mceutik API Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mceutik:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mceutik:${{ github.sha }}
        file: ./Dockerfile
        context: .
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mceutik:latest
        cache-to: type=inline
    
    - name: Clear Docker Build Cache
      run: |
        docker builder prune --force
    
    - name: Create .env file
      run: |
        echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
        echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> .env
        echo "MAIL_DEFAULT_SENDER=${{ secrets.MAIL_DEFAULT_SENDER }}" >> .env
        echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
        echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
        echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
        echo "MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .env
        echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
    
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "docker-compose.yml,nginx.conf,.env"
        target: /home/${{ secrets.EC2_USER }}/projects/freelance/mceutik/
    
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.EC2_USER }}/projects/freelance/mceutik
          
          # Log in to Docker Hub on EC2
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Stop all containers and remove them
          sudo docker-compose down
          
          # Pull latest images
          sudo docker-compose pull
          
          # Start services with the updated configuration
          sudo docker-compose up -d
          
          # Wait for containers to be healthy
          sleep 10
          
          # Clean up old images
          sudo docker image prune -af
          
          # Show container status
          sudo docker-compose ps
        